rules:
  - name: "Protect main branch"
    target: branch
    pattern: main
    enforcement: true
    required_pull_request_reviews:
      required_approving_review_count: 0  # No required reviews
      dismiss_stale_reviews_on_push: false
      require_code_owner_reviews: false
      require_last_push_approval: false
    restrictions:
      users: []
      teams: []
      apps: []
    require_status_checks:
      strict: true
      contexts: []  # Add status checks if you want, otherwise leave empty
    require_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: false
    require_signed_commits: false