version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/backend.simple.Dockerfile
    container_name: agentspy-minimal-backend
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    ports:
      - "8000:8000"
    networks:
      - agentspy-minimal-network

  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/frontend.simple.Dockerfile
    container_name: agentspy-minimal-frontend
    volumes:
      - ../frontend:/workspace/frontend:cached
    working_dir: /workspace/frontend
    # Use supervisor to manage dev server with auto-restart
    command: /usr/local/bin/frontend-supervisor.sh
    ports:
      - "3001:3001"
      - "5173:5173"
    networks:
      - agentspy-minimal-network

networks:
  agentspy-minimal-network:
    driver: bridge
    # below is only needed for podman
    ipam:
      config:
        - subnet: 172.20.0.0/16
    x-podman:
      dns:
        - "8.8.8.8"
        - "8.8.4.4"